### ISSUE TITLE
CDR view policy attributes

### ISSUE THREAD

**Issue by dmitry-sinina** [yeti-switch/yeti-web#1728]
```
      Cdr/Cdr:
        read: true
        pcap: true
        recording: true
        dst_number: true
```

*pcap* - should be true to allow pcap trace download
*recording* - should be true to allow recording download
*dst_number* - should be true to show dst_prefix_in,dst_prefix_routing, dst_prefix_out, legb_ruri. when dst_number=false(by default) then last 3 digits of numbers should be masked
